### ISSUE TITLE
ega palettes

### ISSUE THREAD

**Issue by RetroNick2020** [ascheepe/show#1]
Hello there - it looks like you have done a fair bit of research on ega palettes.

Were you able to get your palette code to work on 320x200x16 and 640x200x16 EGA modes.

I am simply asking because I have tried to do this and the only mode that worked for me was the 640x350x16.

Any idea why EGA palettes don't work on the lesser res modes?

**Comment by ascheepe** [comment]
A quick test with mode 0x0d does seem to work on dosbox. When i use the cga modes it doesn't work however. What mode(hex) did you use?

**Comment by RetroNick2020** [comment]
so you are able to set 16 new colors from the palette of 64?
it's not just cycling through the 16 default colors?
can you do a screen cap of what you see. if you have managed to do this I
am really impressed!

**Comment by ascheepe** [comment]
I've created a small example program. What bit me (again! :) is that it's very important to select the proper memory model so the pointer for plotting is correct, are you sure that's ok in your program too? In turbo c i selected the compact model. If you don't mind cluttering the source you can use a far pointer instead.

![ega_000](https://user-images.githubusercontent.com/76254912/152033712-40c64e42-9961-404b-a40c-db5aacbb6d6b.png)


```
#include <stdio.h>
#include <stdlib.h>
#include <dos.h>

typedef unsigned char BYTE;

struct color {
    BYTE r;
    BYTE g;
    BYTE b;
};

static BYTE *ega_memory = (BYTE *) 0xA0000000L;

void set_mode(int mode) {
    union REGS regs = { 0 };

    regs.h.ah = 0;
    regs.h.al = mode;
    int86(0x10, &regs, &regs);
}
/*
 * EGA stores colors as
 * 7 6 5 4 3 2 1 0
 * | | | | | | | +- Blue  MSB
 * | | | | | | +--- Green MSB
 * | | | | | +----- Red   MSB
 * | | | | +------- Blue  LSB
 * | | | +--------- Green LSB
 * | | +----------- Red   LSB
 * | +------------- Reserved
 * +--------------- Reserved
 */
BYTE ega_make_color(struct color *color) {
    BYTE r = color->r >> 6;
    BYTE g = color->g >> 6;
    BYTE b = color->b >> 6;

    BYTE rmsb = r >> 1;
    BYTE gmsb = g >> 1;
    BYTE bmsb = b >> 1;

    BYTE rlsb = r & 1;
    BYTE glsb = g & 1;
    BYTE blsb = b & 1;

    return (bmsb << 0) | (gmsb << 1) | (rmsb << 2) |
        (blsb << 3) | (glsb << 4) | (rlsb << 5);
}

/*
 * Attribute registers are accessed via I/O port 0x3c0.
 * This register can act like a flip-flop to automatically
 * switch between setting the palette index and the palette
 * value. To enable this mode a read of port 0x3da is
 * required. The datasheet calls this 'sending an IOR command'.
 *
 * After that the first write selects the attribute
 * and the second sets the value.
 *
 * Attributes 0x00 - 0x0F specify the 16 color palette in
 * the format as the make_color function provides.
 */
void ega_set_palette(struct color *palette) {
    int i;

    /* enable 0x3c0 flip-flop */
    (void) inp(0x3da);

    /* and set the palette */
    for (i = 0; i < 16; ++i) {
        outp(0x3c0, i);
        outp(0x3c0, ega_make_color(&palette[i]));
    }
}

/* 2 pixels per byte
 * 320x200x4bits: each row has 320 bits = 320/8 = 40 bytes
 * x byte position therefor is x/320/40 = x/8
 */
void ega_plot(int x, int y, int color) {
    BYTE *pixel = ega_memory + (y << 5) + (y << 3) + (x >> 3);
    BYTE mask = 0x80 >> (x & 7);

    /*
     * color selects which planes to write to
     * this is the palette index value
     * e.g. 11 is cyan with default palette.
     */
    outp(0x3c4, 2);
    outp(0x3c5, color);

    /* set p mask */
    outp(0x3ce, 8);
    outp(0x3cf, mask);

    /*
     * with the mask set above we can just
     * write all 1's
     */
    *pixel |= 0xff;
}

int main(void) {
    struct color palette[16] = {
        { 0, 0,   0 },
        { 0, 0,  16 },
        { 0, 16,  32 },
        { 0, 32,  48 },
        { 0, 48,  64 },
        { 0, 64,  80 },
        { 0, 80,  96 },
        { 0, 96, 112 },
        { 0, 112, 128 },
        { 0, 128, 144 },

        { 0, 144, 160 },
        { 0, 160, 176 },
        { 0, 176, 192 },
        { 0, 192, 208 },
        { 0, 208, 224 },
        { 0, 240, 240 },
    };

    int x;
    int y;
    int color = 0;

    set_mode(0x0d);
    ega_set_palette(palette);

    for (y = 0; y < 200; ++y) {
        for (x = 0; x < 320; ++x) {
            ega_plot(x, y, color);
        }
        color = y & 15;
    }

    getch();
    set_mode(0x03);
    return 0;
}
```

**Comment by RetroNick2020** [comment]
hey thanks for going through all this trouble. but i hate to say it but you
are getting default colors just cycling through.

if you do the same test with the 640x350 screen you can do a side by side
comparison and see the difference.

just because you are able to set the colors without any compiler errors
doesn't mean it's working.

Those are the wrong colors.

**Comment by ascheepe** [comment]
No trouble at all; i see what you mean now but i'm not sure that's entirely correct. When you comment the palette setting you get the default 16 colors but that doesn't seem to include two shades of cyan? (or maybe i'm just not seeing them haha)
The example looks horrible though i agree, i was expecting it to be a better gradient so there's definitely something wrong.

**Comment by RetroNick2020** [comment]
from what i read it is not possible to set a custom (from palette of
64) 16 color palette on 320x200x16 and 640x200x16 modes. you can set 2
or more colors to be the same - but from the same default 16 color
palette.

you are correct and i believe that you can slightly change the
intensity for the first 4 colors but i think that's left over CGA
thing that also works with EGA.

this problem is also easily tested with Microsoft's MSGRAPH library
and Borlands BGI. And i have gone as far as using bios setpalette and
bios putpixel to test this and it all comes out the same way.
everything works as expected in 640x350x16 but not the 320x200 and
640x200 modes

The internet is wrong in many sources for how EGA palettes work. I
have gone over the Ferraro EGA/VGA books and it looks like things are
documented properly there. There is an entire chapter that can explain
things better than i can. I was hoping you found some Michael Abrash
magic code did this.

https://archive.org/details/programmersguidetotheegavgaandsupervgacardsbyrichardf.ferraro19943rdedition/mode/2up

**Comment by ascheepe** [comment]
No you are right, it's indeed the default palette with cga's low and high intensity. Probably the 640x350 mode has issues too in my code, the ega mode is the last thing I added and it's not as easy as the other ones. Thanks a lot for the link!

**Comment by ascheepe** [comment]
The palette changing works only in mode 0x10. I've added a (quick and dirty) test program `egatest.c` which shows the changed palette. Compile with `tcc -mc egatest.c` Hope this is helpful for you :)
